from datetime import datetime
from typing import Optional
from .node import Node

class File(Node):
    content: str
    size: int

    def __init__(
        self,
        name: str,
        parent: Optional[Node] = None,
        created_at: Optional[datetime] = None,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def get_path(self) -> str: ...
    def rename(self, new_name: str) -> None: ...
    def write_content(self, content: str) -> None: ...
    def read_content(self) -> str: ...
    def delete_content(self) -> None: ...
